imports:
    - { resource: ezplatform.yml }

ezpublish:
    system:
        movidiet:
            languages: [fre-FR]
        movidiet_en:
            # In site_authors_sanofi_fr siteaccess, fre-FR is always preferred, and fallback to eng-US if needed.
            languages: [eng-GB, fre-FR]
    siteaccess:
        match:
            Compound\LogicalAnd:
                movidiet:
                    matchers:
                        Map\URI:
                            fr: true
                        Map\Host:
                            movidiet.com: true
                    match: movidiet
                movidiet_en:
                    matchers:
                        Map\URI:
                            en: true
                        Map\Host:
                            movidiet.com: true
                    match: movidiet_en
            Map\Host:
                movidiet.fr: movidiet