login:
    path:   /login
    defaults:  { _controller: ezpublish.security.controller:loginAction }
login_check:
    path:   /login_check
logout:
    path:   /logout

_ezpublishRoutes:
    resource: "@EzPublishCoreBundle/Resources/config/routing/internal.yml"

_ezpublishRestRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix:   "%ezpublish_rest.path_prefix%"

_ezpublishRestOptionsRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix: "%ezpublish_rest.path_prefix%"
    type: rest_options

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_ezpublishPlatformUIRoutes:
    resource: "@eZPlatformUIBundle/Resources/config/routing.yml"

_ezplatformRepositoryFormsRoutes:
    resource: "@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml"

_contentOnTheFly:
    resource: "@ContentOnTheFlyBundle/Resources/config/routing.yml"
    prefix:   "%ezpublish_rest.path_prefix%"

_multiFileUpload:
    resource: "@EzSystemsMultiFileUploadBundle/Resources/config/routing.yml"
    prefix:   "%ezpublish_rest.path_prefix%"

contact-form-ajax:
    path: /add-contact
    methods: [POST]
    defaults: { _controller: AppSiteBundle:Home:contactForm }

follow-index:
    path: /followindex
    defaults: { _controller: AppSiteBundle:Follow:index }

follow-visit-patient:
    path: /visit
    defaults: { _controller: AppSiteBundle:Visit:visit }

follow-visit:
    path: /visit-patient/{userId}
    defaults: { _controller: AppSiteBundle:Visit:visit }

follow-profil-patient:
    path: /profil
    defaults: { _controller: AppSiteBundle:Patient:profil }

follow-profil:
    path: /profil-patient/{userId}
    defaults: { _controller: AppSiteBundle:Patient:profil }

follow-addpatient:
    path: /addpatient
    defaults: { _controller: AppSiteBundle:Patient:addPatient }

follow-disabedpatient:
    path: /disabedpatient/{id}
    defaults: { _controller: AppSiteBundle:Patient:disabledPatient }

follow-change-password:
    path: /changepassword
    defaults: { _controller: AppSiteBundle:Patient:changePassword }

follow-rations-patient:
    path: /ration
    defaults: { _controller: AppSiteBundle:Follow:rations }

follow-rations:
    path: /ration-patient/{userId}
    defaults: { _controller: AppSiteBundle:Follow:rations }

follow-training-patient:
    path: /traning
    defaults: { _controller: AppSiteBundle:Training:training }

follow-training:
    path: /traning-patient/{userId}
    defaults: { _controller: AppSiteBundle:Training:training }

add-visit:
    path: /add-visit
    defaults: { _controller: AppSiteBundle:Visit:addVisit}
    methods:  [POST]

remove-visit:
    path: /remove-visit/{id}/{userId}
    defaults: { _controller: AppSiteBundle:Visit:removeVisit}

add-training:
    path: /add-training
    defaults: { _controller: AppSiteBundle:Training:addTraining}
    methods:  [POST]

remove-training:
    path: /remove-training
    defaults: { _controller: AppSiteBundle:Training:removeTraining}
    methods:  [POST]

edit-profil-patient:
    path: /edit-profil
    defaults: { _controller: AppSiteBundle:Patient:editProfil }

edit-profil:
    path: /edit-profil/{userId}
    defaults: { _controller: AppSiteBundle:Patient:editProfil }

condition-general:
    path: /conditions-generales
    methods: [GET]
    defaults:
        _controller: AppSiteBundle:Home:conditionsGenerales

