parameters:
    app.core_helper.class: App\Bundle\SiteBundle\Helper\CoreHelper
    app.criteria_helper.class: App\Bundle\SiteBundle\Helper\CriteriaHelper
    app.user_helper.class: App\Bundle\SiteBundle\Helper\UserHelper
    app.form.type.contact.class: App\Bundle\SiteBundle\Form\Type\ContactType
    app.form.type.changepassword.class: App\Bundle\SiteBundle\Form\Type\ChangePasswordType
    app.form.type.addpatient.class: App\Bundle\SiteBundle\Form\Type\AddPatientType
    app.form.type.addvisit.class: App\Bundle\SiteBundle\Form\Type\VisitType
    app.login.controller.class: App\Bundle\SiteBundle\Controller\LoginController