parameters:
    app.core_helper.class: App\Bundle\SiteBundle\Helper\CoreHelper
    app.criteria_helper.class: App\Bundle\SiteBundle\Helper\CriteriaHelper
    app.form.type.contact.class: App\Bundle\SiteBundle\Form\Type\ContactType
    app.login.controller.class: App\Bundle\SiteBundle\Controller\LoginController