services:
    app.core_helper:
             class: %app.core_helper.class%
             arguments: [@ezpublish.api.repository, @service_container]
    app.user_helper:
             class: %app.user_helper.class%
             arguments: [@ezpublish.api.repository, @service_container]
    app.criteria_helper:
            class: %app.criteria_helper.class%
            arguments: [@ezpublish.siteaccess]
    app.form.type.contact:
            class: %app.form.type.contact.class%
            tags:
                - { name: form.type, alias: contact_type }
    app.form.type.changepassword:
            class: %app.form.type.changepassword.class%
            arguments: [@translator.default, @ezpublish.api.repository]
            tags:
                - { name: form.type, alias: change_password }
    app.form.type.addpatient:
            class: %app.form.type.addpatient.class%
            arguments: [@translator.default, @ezpublish.api.repository]
            tags:
                - { name: form.type, alias: add_patient }
    app.form.type.addvisit:
            class: %app.form.type.addvisit.class%
            arguments: [@translator.default, @ezpublish.api.repository]
            tags:
                - { name: form.type, alias: add_visit }
    app.security.controller:
            class: "%app.login.controller.class%"
            arguments: ["@templating", "@ezpublish.config.resolver", "@security.authentication_utils", "@service_container"]