services:
    app.core_helper:
             class: %app.core_helper.class%
             arguments: [@ezpublish.api.repository, @service_container]
    app.criteria_helper:
            class: %app.criteria_helper.class%
            arguments: [@ezpublish.siteaccess]
    app.form.type.contact:
            class: %app.form.type.contact.class%
            tags:
                - { name: form.type, alias: contact_type }
    app.security.controller:
            class: "%app.login.controller.class%"
            arguments: ["@templating", "@ezpublish.config.resolver", "@security.authentication_utils", "@service_container"]